version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node