version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123

  msmsrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=secondhand
      - RABBITMQ_DEFAULT_PASS=secondhand