server:
  port: 8503
spring:
  application:
    name: notification-service
    zipkin:
      base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
    rabbitmq:
      username: secondhand
      password: secondhand
    cloud:
      stream:
        bindings:
          input:
            destination: msqueue
eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka/
